language: dart
dart:
- dev

sudo: required

scripts:
- pub run test -p "chrome,vm" test/test_all.dart
- dartanalyzer lib

after_success:
- pub global activate dart_coveralls
- pub global run dart_coveralls report --token $COVERALLS_TOKEN --exclude-test-files test/test_all.dart